easy_admin:
    design:
        menu:
        - { label: 'Workflow', icon: code-fork, route: 'survos_workflows' }
        - { entity: Task }

    entities:
        Task:
            class: App\Entity\Task
            new:
                fields:
                - '-id'
                - '-marking'
                - { property: 'name', type_options: { required: false } }